### ISSUE TITLE
Turn assign_tools into notebook w widgets

### ISSUE THREAD

**Issue by jukent** [jukent/Misc_tools#1]

**Comment by jukent** [comment]
https://github.com/jupyter-widgets/ipywidgets/blob/b2a998402120c2b9a277508efd7453f678c5785e/docs/source/examples/Widget%20List.ipynb

Try SelectMultiple for scale options (maybe user only wants to practice melodic and harmonic minors), that would require changing the line to determine possible scales.

**Comment by andersy005** [comment]
While playing with the ipwidgets (very easy and simple to use :), I got this:

<img width="976" alt="Screen Shot 2019-07-15 at 10 43 00 PM" src="https://user-images.githubusercontent.com/13301940/61266645-fd937600-a751-11e9-8c9f-3a6527ed3c56.png">

**Comment by jukent** [comment]
Thanks Anderson this was helpful! I just changed the widgets used to be a text box for number of scales, and a drop-down menu for modality (since the mapping between values 0,1,2.. to modality isn't meaningful to any users).

Ideally I'd like to change the drop-down menu to a select multiple drop down, with radio-buttons or check boxes for each option. Then the user could request only to practice Major and Harmonic Minor for example. Currently functionality is limited to one or all types of scales. https://github.com/jupyter-widgets/ipywidgets/issues/893 this issue provides some insight into that problem. 

![Screen Shot 2019-07-16 at 10 14 05 AM](https://user-images.githubusercontent.com/46687291/61311055-c86b4000-a7b2-11e9-9d37-b2ccaf9f7f34.png)

**Comment by jukent** [comment]
Satisfied with new widgets for now.
